input_path: "D:/QIP_data"
output_path: "D:/QIP_outputs/all_risk_data.csv"
sheet_names: ["quality_risks_and_issues", "Actions"]
themes:
  indicator_columns: ["title", "description", "consequence", "need", "action", "definition_of_done"]
  dummy_theme:
    dummy_sub_1: ["a", "b", "c"]
    dummy_sub_2: ["d", "e", "f"]
support_owner:
  idicator_columns: ["title", "description", "need", "^action$", "definition_of_done"]
  owners:
    MQD_support: [
      "methodology",
      "automation",
      "coding",
      "method",
      "code",
      "Quality and Improvement Division",
      "reproducible",
      "non-reproducible",
      "\\bDAP\\b",
      "Data Access Platform",
      "DAPCATS",
      "imputation",
      "modelling",
      "quality",
      "training",
      "best practice",
      "good practice",
      "Analytical Standards and Pipelines",
      "BPAI",
      "DQhub",
      "\\bRAPs?\\b",
      "python",
      "^R$",
      "weights",
      "deflator"
      "^MQD$",
      "reweighting"
      ] # concider adding python and ^R$ here too
    Digital_Service_Technology: [
      "Legacy systems",
      "technology",
      "\\bIT\\b",
      "DST",
      "scripts",
      "SQL",
      "SAS",
      "Excel",
      "Existing systems",
      "non-automated systems",
      "Non-strategic systems",
      "\\bDAP\\b",
      "transformation",
      "^IDS$",
      "systems",
      "websites",
      "dashboard",
      "^RTI$",
      "legacy"
      ]
    Surveys: [
      "Surveys",
      "Response Rate",
      "Decline",
      "Sample",
      "Sample size",
      "Falling",
      "coverage",
      "underreporting",
      "BDOD",
      "social surveys",
      "\\bLMS\\b",
      "\\bLFS\\b",
      "^BERD$",
      "^LFS$",
      "^LMS$",
      "survey",
      "Business Enterprise Research and Development"
      ]
    Data_Growth_Operations_or_Data_Acquisitions_Operations: [
      "Data suppliers",
      "Data Growth & Operations",
      "DGO",
      "DAO",
      "Data Acquisitions & Operations",
      "Data availability",
      "Data Access",
      "data sources",
      "data owners",
      "engagement"
      ]
    communication_and_digital_publishing: [
      "Tweets",
      "Communication",
      "communication plan",
      "word count",
      "Articles",
      "Bulletins",
      "word count",
      "QMI",
      "publication",
      "publishing",
      "\\bAPI\\b",
      "web development",
      "content",
      "coherence",
      "harmonised",
      "websites"
      ]
    people_and_business_services: [
      "recruitment",
      "staff",
      "Vacancies",
      "retention",
      "skills",
      "knowledge",
      "turnover",
      "training",
      "capabilit"
      ]
    economic_statistics_change: [
      "RDSA", 
      "\\bDDS\\b", 
      "economic statistics change"
      ]
